name: predict_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - absl-py==0.13.0
  - attrs==22.2.0
  - beautifulsoup4==4.12.3
  - cached-property==1.5.2
  - cachetools==4.2.2
  - cads-api-client==1.0.3
  - cdsapi==0.7.0
  - certifi==2020.12.5
  - cftime==1.6.0
  - charset-normalizer==2.0.4
  - click==8.0.4
  - colorama==0.4.4
  - cycler==0.10.0
  - dataclasses @ file:///tmp/build/80754af9/dataclasses_1614363715916/work
  - decorator==4.4.2
  - dill==0.3.4
  - einops==0.4.1
  - EMD-signal==1.5.2
  - et-xmlfile==1.1.0
  - Flask==2.0.3
  - future==0.18.2
  - GDAL==2.3.2
  - google-auth==1.34.0
  - google-auth-oauthlib==0.4.5
  - grpcio==1.39.0
  - h5py==3.1.0
  - idna==3.2
  - imageio==2.9.0
  - importlib-metadata==4.6.3
  - importlib-resources==5.4.0
  - itsdangerous==2.0.1
  - Jinja2==3.0.3
  - joblib==1.0.1
  - keras==2.10.0
  - kiwisolver==1.3.1
  - linformer==0.2.3
  - lpips==0.1.3
  - Markdown==3.3.4
  - MarkupSafe==2.0.1
  - matplotlib==3.3.4
  - missingno==0.5.2
  - mkl-fft==1.3.0
  - mkl-random==1.1.1
  - mkl-service==2.3.0
  - multiprocess==0.70.12.2
  - multiurl==0.3.1
  - netCDF4==1.6.2
  - networkx==2.5.1
  - numpy @ file:///C:/ci/numpy_and_numpy_base_1603480701039/work
  - oauthlib==3.1.1
  - olefile==0.46
  - opencv-contrib-python==3.3.0.10
  - openpyxl==3.1.3
  - pandas @ file:///C:/ci/pandas_1608056614942/work
  - pathos==0.2.8
  - patsy==0.5.6
  - Pillow @ file:///C:/ci/pillow_1615224175364/work
  - pox==0.3.0
  - ppft==1.6.6.4
  - protobuf==3.17.3
  - Py6S==1.9.2
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pyparsing==2.4.7
  - pysolar==0.11
  - python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
  - pytz==2021.3
  - PyWavelets==1.1.1
  - requests==2.26.0
  - requests-oauthlib==1.3.0
  - rsa==4.7.2
  - scikit-image==0.17.2
  - scikit-learn==0.24.2
  - scipy==1.5.4
  - seaborn==0.11.2
  - six @ file:///home/linux1/recipes/ci/six_1610970791821/work
  - soupsieve==2.3.2.post1
  - statsmodels==0.12.2
  - tensorboard==2.5.0
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.0
  - tensorboardX==2.5.1
  - threadpoolctl==2.2.0
  - tifffile==2020.9.3
  - torch==1.8.1
  - torchaudio==0.8.1
  - torchsummary==1.5.1
  - torchvision==0.9.1
  - tqdm==4.64.1
  - typing-extensions @ file:///home/ktietz/src/ci_mi/typing_extensions_1612808209620/work
  - urllib3==1.26.6
  - Werkzeug==2.0.1
  - wincertstore==0.2
  - xlrd==2.0.1
  - zipp==3.5.0
